# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            rohan
tagline:          'dunno what this does'
description:      'Occasionally write at length about compilers, rust, and programming languages.'
url:              https://srohanjd.com
baseurl:          /

author:
  name:           'Rohan Janaki'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/darklyspaced/
